-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 14:27:44 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema srs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `srs` ;
CREATE SCHEMA IF NOT EXISTS `srs` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `srs` ;

-- -----------------------------------------------------
-- Table `srs`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`users` ;

CREATE TABLE IF NOT EXISTS `srs`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(90) NOT NULL,
  `hashed_password` VARCHAR(90) NOT NULL,
  `role` INTEGER NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `gender` TINYINT NULL,
  `dob` DATE NULL,
  `avatar` VARCHAR(180) NULL,
  `registered_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `srs`.`users` (`email` ASC);

CREATE INDEX `users_email_idx` ON `srs`.`users` (`email` ASC);


-- -----------------------------------------------------
-- Table `srs`.`schools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`schools` ;

CREATE TABLE IF NOT EXISTS `srs`.`schools` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `school_type` VARCHAR(45) NULL,
  `address_line1` VARCHAR(90) NULL,
  `address_line2` VARCHAR(90) NULL,
  `address_line3` VARCHAR(90) NULL,
  `postcode` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`teachers` ;

CREATE TABLE IF NOT EXISTS `srs`.`teachers` (
  `user_id` INT(11) NOT NULL,
  `school_id` INT(11) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_teachers_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `srs`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teachers_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `srs`.`schools` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_teachers_school_id_idx` ON `srs`.`teachers` (`school_id` ASC);


-- -----------------------------------------------------
-- Table `srs`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`students` ;

CREATE TABLE IF NOT EXISTS `srs`.`students` (
  `user_id` INT(11) NOT NULL,
  `school_id` INT(11) NULL,
  `teacher_id` INT(11) NULL,
  `address_line1` VARCHAR(90) NULL,
  `address_line2` VARCHAR(90) NULL,
  `address_line3` VARCHAR(90) NULL,
  `postcode` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_students_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `srs`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_students_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `srs`.`schools` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_students_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `srs`.`teachers` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_students_school_id_idx` ON `srs`.`students` (`school_id` ASC);

CREATE INDEX `fk_students_teacher_id_idx` ON `srs`.`students` (`teacher_id` ASC);


-- -----------------------------------------------------
-- Table `srs`.`buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`buildings` ;

CREATE TABLE IF NOT EXISTS `srs`.`buildings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `map_no` INT(11) NULL,
  `longitude` DECIMAL(9,6) NULL,
  `latitude` DECIMAL(9,6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`departments` ;

CREATE TABLE IF NOT EXISTS `srs`.`departments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `building_id` INT(11) NULL,
  `address_line1` VARCHAR(90) NULL,
  `address_line2` VARCHAR(90) NULL,
  `address_line3` VARCHAR(90) NULL,
  `postcode` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_departments_building_id`
    FOREIGN KEY (`building_id`)
    REFERENCES `srs`.`buildings` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_departments_building_id_idx` ON `srs`.`departments` (`building_id` ASC);


-- -----------------------------------------------------
-- Table `srs`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`staff` ;

CREATE TABLE IF NOT EXISTS `srs`.`staff` (
  `user_id` INT(11) NOT NULL,
  `department_id` INT(11) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_staff_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `srs`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_staff_department_id`
    FOREIGN KEY (`department_id`)
    REFERENCES `srs`.`departments` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_staff_department_id_idx` ON `srs`.`staff` (`department_id` ASC);


-- -----------------------------------------------------
-- Table `srs`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`admins` ;

CREATE TABLE IF NOT EXISTS `srs`.`admins` (
  `user_id` INT(11) NOT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_admins_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `srs`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`rooms` ;

CREATE TABLE IF NOT EXISTS `srs`.`rooms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(45) NOT NULL,
  `room_no` VARCHAR(45) NULL,
  `building_id` INT(11) NULL,
  `size` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_rooms_building_id`
    FOREIGN KEY (`building_id`)
    REFERENCES `srs`.`buildings` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_rooms_building_id_idx` ON `srs`.`rooms` (`building_id` ASC);


-- -----------------------------------------------------
-- Table `srs`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`events` ;

CREATE TABLE IF NOT EXISTS `srs`.`events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(180) NOT NULL,
  `description` TEXT NOT NULL,
  `type` VARCHAR(80) NULL,
  `tags` VARCHAR(180) NULL,
  `room_id` INT(11) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `proposed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `proposed_by` INT(11) NULL,
  `approved_at` DATETIME NULL,
  `approved_by` INT(11) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'pending',
  `applicants` INT(11) NOT NULL DEFAULT 0,
  `facebook_link` VARCHAR(180) NULL,
  `twitter_link` VARCHAR(180) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_events_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `srs`.`rooms` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_events_proposed_by`
    FOREIGN KEY (`proposed_by`)
    REFERENCES `srs`.`staff` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_events_approved_by`
    FOREIGN KEY (`approved_by`)
    REFERENCES `srs`.`admins` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_events_room_id_idx` ON `srs`.`events` (`room_id` ASC);

CREATE INDEX `fk_events_approved_by_idx` ON `srs`.`events` (`approved_by` ASC);

CREATE INDEX `events_start_time_idx` ON `srs`.`events` (`start_time` ASC);

CREATE INDEX `events_proposed_at_idx` ON `srs`.`events` (`approved_at` ASC);

CREATE INDEX `fk_events_proposed_by_idx` ON `srs`.`events` (`proposed_by` ASC);


-- -----------------------------------------------------
-- Table `srs`.`applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`applications` ;

CREATE TABLE IF NOT EXISTS `srs`.`applications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NULL,
  `event_id` INT(11) NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'reserved',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_applications_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `srs`.`students` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_applications_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `srs`.`events` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE INDEX `fk_applications_student_id_idx` ON `srs`.`applications` (`student_id` ASC);

CREATE INDEX `fk_applications_event_id_idx` ON `srs`.`applications` (`event_id` ASC);


-- -----------------------------------------------------
-- Table `srs`.`feedbacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`feedbacks` ;

CREATE TABLE IF NOT EXISTS `srs`.`feedbacks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NULL,
  `comment` TEXT NULL,
  `submit_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_feedbacks_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `srs`.`students` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_feedbacks_student_id_idx` ON `srs`.`feedbacks` (`student_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
